### ISSUE TITLE
Can't make Accept working

### ISSUE THREAD

**Issue by qdev89** [jamestiotio/CITM#2]
hi @jamestiotio
I followed your instruction but stuck on last step where we have to set Header Response to this
![image](https://user-images.githubusercontent.com/1589871/71762377-16ab0180-2f01-11ea-9d9e-1525ce95d206.png)
![image](https://user-images.githubusercontent.com/1589871/71762428-9d5fde80-2f01-11ea-8e08-1d3ff2bed913.png)

It returns to 200 OK as you can see but on the game client, it's still throwing this error message

I'm pretty sure header repsone is matched with GET that I made with Content-Length: 337(337 is exact number bytes I sent on GET)
![image](https://user-images.githubusercontent.com/1589871/71762431-a51f8300-2f01-11ea-82ea-1fec14138ff8.png)

My item to claim:
`[ 
   { 
      "id":1,
      "accountId":"50b8832e0",
      "title":"Items",
      "body":"",
      "clientVersion":90100,
      "country":"en",
      "accepted":null,
      "created":1578117644,
      "items":[ 
         { 
            "itemId":5,
    "itemCategory":1,
    "amount":100,
    "title":"Bird Cat"
         }
      ]
   }
]`

Please help me if I'm doing wrong.
Thanks and best regards.

**Comment by jamestiotio** [comment]
Hi @quocfreelancer, you would need to do it quickly as well since there is an inherent timeout. If you take too much time, it will still return a 200 in Fiddler but Battle Cats will throw that error.

You can try copying the header from the `HexView` tab, if that helps.

Your item list looks fine.

Also, I suggest that you hide your `accountId`. Cheers!

**Comment by SuperHKA** [comment]
Hi @jamestiotio is this patched or not ?

**Comment by jamestiotio** [comment]
Hi @AndreReboulet, are you referring to the inherent timeout highlighted in this issue or to the overall hack?

If you are referring to the inherent timeout, there is no way to bypass or "patch" that timeout since it is built-in into the whole Battle Cats application code (and might also be in its server code as well).

If you are referring to the overall hack, it is still working as of today (I just checked). I have updated the appropriate JSON lines and added new cats to the Cat List to accommodate version 9.4.0 of Battle Cats in the commit beb63f578e25e488686bd42fe4ed35f5cdcca16d. Do observe the ```clientVersion``` pattern carefully and feel free to PR occasional updates to the Cat List since I would not be able to update this repo on a very frequent basis. Please also do open a new issue next time if you are highlighting a separate topic.

Otherwise, I will be closing this issue. Feel free to re-open if my previous reply was unsatisfactory.
